// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Label label1;
    
    private Gtk.Entry entry1;
    
    private Gtk.Button button1;
    
    private Gtk.HBox hbox4;
    
    private Gtk.Label label2;
    
    private Gtk.Entry entry2;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Label label7;
    
    private Gtk.ComboBoxEntry comboboxentry1;
    
    private Gtk.Label label8;
    
    private Gtk.Entry entry4;
    
    private Gtk.Button button2;
    
    private Gtk.HBox hbox5;
    
    private Gtk.Label label3;
    
    private Gtk.Entry entry3;
    
    private Gtk.HPaned hpaned1;
    
    private Gtk.VBox vbox3;
    
    private Gtk.HBox hbox6;
    
    private Gtk.Notebook notebook2;
    
    private Gtk.Label label21;
    
    private Gtk.Label label28;
    
    private Gtk.Label label29;
    
    private Gtk.Label label30;
    
    private Gtk.Label label31;
    
    private Gtk.Label label32;
    
    private Gtk.Label label33;
    
    private Gtk.HPaned hpaned2;
    
    private Gtk.VBox vbox5;
    
    private Gtk.HBox hbox15;
    
    private Gtk.Notebook notebook1;
    
    private Gtk.Image image1;
    
    private Gtk.Label label9;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.TextView textview2;
    
    private Gtk.Label label23;
    
    private Gtk.ScrolledWindow GtkScrolledWindow1;
    
    private Gtk.TextView textview1;
    
    private Gtk.Label label24;
    
    private Gtk.DrawingArea drawingarea1;
    
    private Gtk.Label label25;
    
    private Gtk.Label label26;
    
    private Gtk.Label label27;
    
    private Gtk.VBox vbox4;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Notebook notebook3;
    
    private Gtk.VBox vbox2;
    
    private Gtk.HBox hbox11;
    
    private Gtk.Label label14;
    
    private Gtk.Entry entry5;
    
    private Gtk.HBox hbox7;
    
    private Gtk.Label label15;
    
    private Gtk.ColorButton colorbutton2;
    
    private Gtk.HBox hbox8;
    
    private Gtk.Label label20;
    
    private Gtk.ComboBoxEntry comboboxentry2;
    
    private Gtk.HBox hbox13;
    
    private Gtk.Label label16;
    
    private Gtk.SpinButton spinbutton1;
    
    private Gtk.HBox hbox9;
    
    private Gtk.Label label17;
    
    private Gtk.HBox hbox10;
    
    private Gtk.Entry entry7;
    
    private Gtk.Label label18;
    
    private Gtk.HBox hbox12;
    
    private Gtk.Entry entry8;
    
    private Gtk.Label label19;
    
    private Gtk.HBox hbox14;
    
    private Gtk.Button button3;
    
    private Gtk.Label label5;
    
    private Gtk.Label label6;
    
    private Gtk.Label label22;
    
    private Gtk.Label label10;
    
    private Gtk.Label label11;
    
    private Gtk.Label label12;
    
    private Gtk.Label label13;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("In File");
        this.hbox3.Add(this.label1);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox3[this.label1]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        w1.Padding = ((uint)(6));
        // Container child hbox3.Gtk.Box+BoxChild
        this.entry1 = new Gtk.Entry();
        this.entry1.CanFocus = true;
        this.entry1.Name = "entry1";
        this.entry1.Text = Mono.Unix.Catalog.GetString("/home/dave/Projects/Mimagemagick/Mimagemagick/bin/Debug/in.jpg");
        this.entry1.IsEditable = true;
        this.entry1.InvisibleChar = '●';
        this.hbox3.Add(this.entry1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.entry1]));
        w2.Position = 1;
        // Container child hbox3.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("button1");
        this.hbox3.Add(this.button1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox3[this.button1]));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        w3.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox3);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
        w4.Position = 0;
        w4.Expand = false;
        w4.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 6;
        // Container child hbox4.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Out File");
        this.hbox4.Add(this.label2);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox4[this.label2]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        w5.Padding = ((uint)(6));
        // Container child hbox4.Gtk.Box+BoxChild
        this.entry2 = new Gtk.Entry();
        this.entry2.CanFocus = true;
        this.entry2.Name = "entry2";
        this.entry2.Text = Mono.Unix.Catalog.GetString("/home/dave/Projects/Mimagemagick/Mimagemagick/bin/Debug/out.jpg");
        this.entry2.IsEditable = true;
        this.entry2.InvisibleChar = '●';
        this.hbox4.Add(this.entry2);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox4[this.entry2]));
        w6.Position = 1;
        w6.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox4);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
        w7.Position = 1;
        w7.Expand = false;
        w7.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.label7 = new Gtk.Label();
        this.label7.Name = "label7";
        this.label7.LabelProp = Mono.Unix.Catalog.GetString("Option");
        this.hbox1.Add(this.label7);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox1[this.label7]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        w8.Padding = ((uint)(6));
        // Container child hbox1.Gtk.Box+BoxChild
        this.comboboxentry1 = Gtk.ComboBoxEntry.NewText();
        this.comboboxentry1.Name = "comboboxentry1";
        this.hbox1.Add(this.comboboxentry1);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox1[this.comboboxentry1]));
        w9.Position = 1;
        w9.Expand = false;
        w9.Fill = false;
        w9.Padding = ((uint)(6));
        // Container child hbox1.Gtk.Box+BoxChild
        this.label8 = new Gtk.Label();
        this.label8.Name = "label8";
        this.label8.LabelProp = Mono.Unix.Catalog.GetString("Value");
        this.hbox1.Add(this.label8);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox1[this.label8]));
        w10.Position = 2;
        w10.Expand = false;
        w10.Fill = false;
        w10.Padding = ((uint)(6));
        // Container child hbox1.Gtk.Box+BoxChild
        this.entry4 = new Gtk.Entry();
        this.entry4.CanFocus = true;
        this.entry4.Name = "entry4";
        this.entry4.IsEditable = true;
        this.entry4.InvisibleChar = '●';
        this.hbox1.Add(this.entry4);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.entry4]));
        w11.Position = 3;
        // Container child hbox1.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("Append");
        this.hbox1.Add(this.button2);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox1[this.button2]));
        w12.Position = 4;
        w12.Expand = false;
        w12.Fill = false;
        w12.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w13.Position = 2;
        w13.Expand = false;
        w13.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        // Container child hbox5.Gtk.Box+BoxChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Options");
        this.hbox5.Add(this.label3);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox5[this.label3]));
        w14.Position = 0;
        w14.Expand = false;
        w14.Fill = false;
        w14.Padding = ((uint)(6));
        // Container child hbox5.Gtk.Box+BoxChild
        this.entry3 = new Gtk.Entry();
        this.entry3.CanFocus = true;
        this.entry3.Name = "entry3";
        this.entry3.Text = Mono.Unix.Catalog.GetString("-resize 100% -gamma 1.5 -flop -border 5x5 -bordercolor \"#000000\" -verbose -debug \"all\"");
        this.entry3.IsEditable = true;
        this.entry3.InvisibleChar = '●';
        this.hbox5.Add(this.entry3);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox5[this.entry3]));
        w15.Position = 1;
        w15.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox5);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
        w16.Position = 3;
        w16.Expand = false;
        w16.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hpaned1 = new Gtk.HPaned();
        this.hpaned1.CanFocus = true;
        this.hpaned1.Name = "hpaned1";
        this.hpaned1.Position = 253;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox6 = new Gtk.HBox();
        this.hbox6.Name = "hbox6";
        this.hbox6.Spacing = 6;
        // Container child hbox6.Gtk.Box+BoxChild
        this.notebook2 = new Gtk.Notebook();
        this.notebook2.CanFocus = true;
        this.notebook2.Name = "notebook2";
        this.notebook2.CurrentPage = 0;
        this.notebook2.TabPos = ((Gtk.PositionType)(1));
        // Notebook tab
        Gtk.Label w17 = new Gtk.Label();
        w17.Visible = true;
        this.notebook2.Add(w17);
        this.label21 = new Gtk.Label();
        this.label21.Name = "label21";
        this.label21.LabelProp = Mono.Unix.Catalog.GetString("page1");
        this.notebook2.SetTabLabel(w17, this.label21);
        this.label21.ShowAll();
        // Notebook tab
        Gtk.Label w18 = new Gtk.Label();
        w18.Visible = true;
        this.notebook2.Add(w18);
        this.label28 = new Gtk.Label();
        this.label28.Name = "label28";
        this.label28.LabelProp = Mono.Unix.Catalog.GetString("page2");
        this.notebook2.SetTabLabel(w18, this.label28);
        this.label28.ShowAll();
        // Notebook tab
        Gtk.Label w19 = new Gtk.Label();
        w19.Visible = true;
        this.notebook2.Add(w19);
        this.label29 = new Gtk.Label();
        this.label29.Name = "label29";
        this.label29.LabelProp = Mono.Unix.Catalog.GetString("page3");
        this.notebook2.SetTabLabel(w19, this.label29);
        this.label29.ShowAll();
        // Notebook tab
        Gtk.Label w20 = new Gtk.Label();
        w20.Visible = true;
        this.notebook2.Add(w20);
        this.label30 = new Gtk.Label();
        this.label30.Name = "label30";
        this.label30.LabelProp = Mono.Unix.Catalog.GetString("page4");
        this.notebook2.SetTabLabel(w20, this.label30);
        this.label30.ShowAll();
        // Notebook tab
        Gtk.Label w21 = new Gtk.Label();
        w21.Visible = true;
        this.notebook2.Add(w21);
        this.label31 = new Gtk.Label();
        this.label31.Name = "label31";
        this.label31.LabelProp = Mono.Unix.Catalog.GetString("page5");
        this.notebook2.SetTabLabel(w21, this.label31);
        this.label31.ShowAll();
        // Notebook tab
        Gtk.Label w22 = new Gtk.Label();
        w22.Visible = true;
        this.notebook2.Add(w22);
        this.label32 = new Gtk.Label();
        this.label32.Name = "label32";
        this.label32.LabelProp = Mono.Unix.Catalog.GetString("page6");
        this.notebook2.SetTabLabel(w22, this.label32);
        this.label32.ShowAll();
        // Notebook tab
        Gtk.Label w23 = new Gtk.Label();
        w23.Visible = true;
        this.notebook2.Add(w23);
        this.label33 = new Gtk.Label();
        this.label33.Name = "label33";
        this.label33.LabelProp = Mono.Unix.Catalog.GetString("page7");
        this.notebook2.SetTabLabel(w23, this.label33);
        this.label33.ShowAll();
        this.hbox6.Add(this.notebook2);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox6[this.notebook2]));
        w24.Position = 0;
        w24.Padding = ((uint)(6));
        this.vbox3.Add(this.hbox6);
        Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
        w25.Position = 0;
        w25.Padding = ((uint)(6));
        this.hpaned1.Add(this.vbox3);
        Gtk.Paned.PanedChild w26 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.vbox3]));
        w26.Resize = false;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.hpaned2 = new Gtk.HPaned();
        this.hpaned2.CanFocus = true;
        this.hpaned2.Name = "hpaned2";
        this.hpaned2.Position = 404;
        // Container child hpaned2.Gtk.Paned+PanedChild
        this.vbox5 = new Gtk.VBox();
        this.vbox5.Name = "vbox5";
        this.vbox5.Spacing = 6;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox15 = new Gtk.HBox();
        this.hbox15.Name = "hbox15";
        this.hbox15.Spacing = 6;
        // Container child hbox15.Gtk.Box+BoxChild
        this.notebook1 = new Gtk.Notebook();
        this.notebook1.CanFocus = true;
        this.notebook1.Name = "notebook1";
        this.notebook1.CurrentPage = 0;
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.image1 = new Gtk.Image();
        this.image1.Name = "image1";
        this.notebook1.Add(this.image1);
        // Notebook tab
        this.label9 = new Gtk.Label();
        this.label9.Name = "label9";
        this.label9.LabelProp = Mono.Unix.Catalog.GetString("page1");
        this.notebook1.SetTabLabel(this.image1, this.label9);
        this.label9.ShowAll();
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.textview2 = new Gtk.TextView();
        this.textview2.CanFocus = true;
        this.textview2.Name = "textview2";
        this.GtkScrolledWindow.Add(this.textview2);
        this.notebook1.Add(this.GtkScrolledWindow);
        Gtk.Notebook.NotebookChild w29 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.GtkScrolledWindow]));
        w29.Position = 1;
        // Notebook tab
        this.label23 = new Gtk.Label();
        this.label23.Name = "label23";
        this.label23.LabelProp = Mono.Unix.Catalog.GetString("page2");
        this.notebook1.SetTabLabel(this.GtkScrolledWindow, this.label23);
        this.label23.ShowAll();
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
        this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
        this.textview1 = new Gtk.TextView();
        this.textview1.CanFocus = true;
        this.textview1.Name = "textview1";
        this.textview1.WrapMode = ((Gtk.WrapMode)(1));
        this.GtkScrolledWindow1.Add(this.textview1);
        this.notebook1.Add(this.GtkScrolledWindow1);
        Gtk.Notebook.NotebookChild w31 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.GtkScrolledWindow1]));
        w31.Position = 2;
        // Notebook tab
        this.label24 = new Gtk.Label();
        this.label24.Name = "label24";
        this.label24.LabelProp = Mono.Unix.Catalog.GetString("page3");
        this.notebook1.SetTabLabel(this.GtkScrolledWindow1, this.label24);
        this.label24.ShowAll();
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.drawingarea1 = new Gtk.DrawingArea();
        this.drawingarea1.Name = "drawingarea1";
        this.notebook1.Add(this.drawingarea1);
        Gtk.Notebook.NotebookChild w32 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.drawingarea1]));
        w32.Position = 3;
        // Notebook tab
        this.label25 = new Gtk.Label();
        this.label25.Name = "label25";
        this.label25.LabelProp = Mono.Unix.Catalog.GetString("page4");
        this.notebook1.SetTabLabel(this.drawingarea1, this.label25);
        this.label25.ShowAll();
        // Notebook tab
        Gtk.Label w33 = new Gtk.Label();
        w33.Visible = true;
        this.notebook1.Add(w33);
        this.label26 = new Gtk.Label();
        this.label26.Name = "label26";
        this.label26.LabelProp = Mono.Unix.Catalog.GetString("page5");
        this.notebook1.SetTabLabel(w33, this.label26);
        this.label26.ShowAll();
        // Notebook tab
        Gtk.Label w34 = new Gtk.Label();
        w34.Visible = true;
        this.notebook1.Add(w34);
        this.label27 = new Gtk.Label();
        this.label27.Name = "label27";
        this.label27.LabelProp = Mono.Unix.Catalog.GetString("page6");
        this.notebook1.SetTabLabel(w34, this.label27);
        this.label27.ShowAll();
        this.hbox15.Add(this.notebook1);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.hbox15[this.notebook1]));
        w35.Position = 0;
        w35.Padding = ((uint)(6));
        this.vbox5.Add(this.hbox15);
        Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox15]));
        w36.Position = 0;
        w36.Padding = ((uint)(6));
        this.hpaned2.Add(this.vbox5);
        Gtk.Paned.PanedChild w37 = ((Gtk.Paned.PanedChild)(this.hpaned2[this.vbox5]));
        w37.Resize = false;
        // Container child hpaned2.Gtk.Paned+PanedChild
        this.vbox4 = new Gtk.VBox();
        this.vbox4.Name = "vbox4";
        this.vbox4.Spacing = 6;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.notebook3 = new Gtk.Notebook();
        this.notebook3.CanFocus = true;
        this.notebook3.Name = "notebook3";
        this.notebook3.CurrentPage = 0;
        this.notebook3.TabPos = ((Gtk.PositionType)(0));
        // Container child notebook3.Gtk.Notebook+NotebookChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox11 = new Gtk.HBox();
        this.hbox11.Name = "hbox11";
        this.hbox11.Spacing = 6;
        // Container child hbox11.Gtk.Box+BoxChild
        this.label14 = new Gtk.Label();
        this.label14.Name = "label14";
        this.label14.LabelProp = Mono.Unix.Catalog.GetString("Text");
        this.hbox11.Add(this.label14);
        Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.hbox11[this.label14]));
        w38.Position = 0;
        w38.Expand = false;
        w38.Fill = false;
        w38.Padding = ((uint)(6));
        // Container child hbox11.Gtk.Box+BoxChild
        this.entry5 = new Gtk.Entry();
        this.entry5.CanFocus = true;
        this.entry5.Name = "entry5";
        this.entry5.IsEditable = true;
        this.entry5.InvisibleChar = '●';
        this.hbox11.Add(this.entry5);
        Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(this.hbox11[this.entry5]));
        w39.PackType = ((Gtk.PackType)(1));
        w39.Position = 1;
        w39.Expand = false;
        w39.Padding = ((uint)(6));
        this.vbox2.Add(this.hbox11);
        Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox11]));
        w40.Position = 0;
        w40.Expand = false;
        w40.Fill = false;
        w40.Padding = ((uint)(3));
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox7 = new Gtk.HBox();
        this.hbox7.Name = "hbox7";
        this.hbox7.Spacing = 6;
        // Container child hbox7.Gtk.Box+BoxChild
        this.label15 = new Gtk.Label();
        this.label15.Name = "label15";
        this.label15.LabelProp = Mono.Unix.Catalog.GetString("Color");
        this.hbox7.Add(this.label15);
        Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(this.hbox7[this.label15]));
        w41.Position = 0;
        w41.Expand = false;
        w41.Fill = false;
        w41.Padding = ((uint)(6));
        // Container child hbox7.Gtk.Box+BoxChild
        this.colorbutton2 = new Gtk.ColorButton();
        this.colorbutton2.CanFocus = true;
        this.colorbutton2.Events = ((Gdk.EventMask)(784));
        this.colorbutton2.Name = "colorbutton2";
        this.hbox7.Add(this.colorbutton2);
        Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.hbox7[this.colorbutton2]));
        w42.PackType = ((Gtk.PackType)(1));
        w42.Position = 1;
        w42.Padding = ((uint)(6));
        this.vbox2.Add(this.hbox7);
        Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox7]));
        w43.Position = 1;
        w43.Expand = false;
        w43.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox8 = new Gtk.HBox();
        this.hbox8.Name = "hbox8";
        this.hbox8.Spacing = 6;
        // Container child hbox8.Gtk.Box+BoxChild
        this.label20 = new Gtk.Label();
        this.label20.Name = "label20";
        this.label20.LabelProp = Mono.Unix.Catalog.GetString("Font");
        this.hbox8.Add(this.label20);
        Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.hbox8[this.label20]));
        w44.Position = 0;
        w44.Expand = false;
        w44.Fill = false;
        w44.Padding = ((uint)(6));
        // Container child hbox8.Gtk.Box+BoxChild
        this.comboboxentry2 = Gtk.ComboBoxEntry.NewText();
        this.comboboxentry2.Name = "comboboxentry2";
        this.hbox8.Add(this.comboboxentry2);
        Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.hbox8[this.comboboxentry2]));
        w45.PackType = ((Gtk.PackType)(1));
        w45.Position = 1;
        w45.Expand = false;
        w45.Fill = false;
        w45.Padding = ((uint)(6));
        this.vbox2.Add(this.hbox8);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox8]));
        w46.Position = 2;
        w46.Expand = false;
        w46.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox13 = new Gtk.HBox();
        this.hbox13.Name = "hbox13";
        this.hbox13.Spacing = 6;
        // Container child hbox13.Gtk.Box+BoxChild
        this.label16 = new Gtk.Label();
        this.label16.Name = "label16";
        this.label16.LabelProp = Mono.Unix.Catalog.GetString("Size");
        this.hbox13.Add(this.label16);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.hbox13[this.label16]));
        w47.Position = 0;
        w47.Expand = false;
        w47.Fill = false;
        w47.Padding = ((uint)(6));
        // Container child hbox13.Gtk.Box+BoxChild
        this.spinbutton1 = new Gtk.SpinButton(0, 100, 1);
        this.spinbutton1.CanFocus = true;
        this.spinbutton1.Name = "spinbutton1";
        this.spinbutton1.Adjustment.PageIncrement = 10;
        this.spinbutton1.ClimbRate = 1;
        this.spinbutton1.Numeric = true;
        this.spinbutton1.Value = 14;
        this.hbox13.Add(this.spinbutton1);
        Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.hbox13[this.spinbutton1]));
        w48.PackType = ((Gtk.PackType)(1));
        w48.Position = 1;
        w48.Expand = false;
        w48.Fill = false;
        w48.Padding = ((uint)(6));
        this.vbox2.Add(this.hbox13);
        Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox13]));
        w49.Position = 3;
        w49.Expand = false;
        w49.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox9 = new Gtk.HBox();
        this.hbox9.Name = "hbox9";
        this.hbox9.Spacing = 6;
        // Container child hbox9.Gtk.Box+BoxChild
        this.label17 = new Gtk.Label();
        this.label17.Name = "label17";
        this.label17.LabelProp = Mono.Unix.Catalog.GetString("Position");
        this.hbox9.Add(this.label17);
        Gtk.Box.BoxChild w50 = ((Gtk.Box.BoxChild)(this.hbox9[this.label17]));
        w50.Position = 0;
        w50.Expand = false;
        w50.Fill = false;
        w50.Padding = ((uint)(6));
        this.vbox2.Add(this.hbox9);
        Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox9]));
        w51.Position = 4;
        w51.Expand = false;
        w51.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox10 = new Gtk.HBox();
        this.hbox10.Name = "hbox10";
        this.hbox10.Spacing = 6;
        // Container child hbox10.Gtk.Box+BoxChild
        this.entry7 = new Gtk.Entry();
        this.entry7.CanFocus = true;
        this.entry7.Name = "entry7";
        this.entry7.IsEditable = true;
        this.entry7.InvisibleChar = '●';
        this.hbox10.Add(this.entry7);
        Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(this.hbox10[this.entry7]));
        w52.PackType = ((Gtk.PackType)(1));
        w52.Position = 1;
        w52.Expand = false;
        w52.Padding = ((uint)(6));
        // Container child hbox10.Gtk.Box+BoxChild
        this.label18 = new Gtk.Label();
        this.label18.Name = "label18";
        this.label18.LabelProp = Mono.Unix.Catalog.GetString("X");
        this.hbox10.Add(this.label18);
        Gtk.Box.BoxChild w53 = ((Gtk.Box.BoxChild)(this.hbox10[this.label18]));
        w53.PackType = ((Gtk.PackType)(1));
        w53.Position = 2;
        w53.Expand = false;
        w53.Fill = false;
        this.vbox2.Add(this.hbox10);
        Gtk.Box.BoxChild w54 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox10]));
        w54.Position = 5;
        w54.Expand = false;
        w54.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox12 = new Gtk.HBox();
        this.hbox12.Name = "hbox12";
        this.hbox12.Spacing = 6;
        // Container child hbox12.Gtk.Box+BoxChild
        this.entry8 = new Gtk.Entry();
        this.entry8.CanFocus = true;
        this.entry8.Name = "entry8";
        this.entry8.IsEditable = true;
        this.entry8.InvisibleChar = '●';
        this.hbox12.Add(this.entry8);
        Gtk.Box.BoxChild w55 = ((Gtk.Box.BoxChild)(this.hbox12[this.entry8]));
        w55.PackType = ((Gtk.PackType)(1));
        w55.Position = 1;
        w55.Expand = false;
        w55.Padding = ((uint)(6));
        // Container child hbox12.Gtk.Box+BoxChild
        this.label19 = new Gtk.Label();
        this.label19.Name = "label19";
        this.label19.LabelProp = Mono.Unix.Catalog.GetString("Y");
        this.hbox12.Add(this.label19);
        Gtk.Box.BoxChild w56 = ((Gtk.Box.BoxChild)(this.hbox12[this.label19]));
        w56.PackType = ((Gtk.PackType)(1));
        w56.Position = 2;
        w56.Expand = false;
        w56.Fill = false;
        this.vbox2.Add(this.hbox12);
        Gtk.Box.BoxChild w57 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox12]));
        w57.Position = 6;
        w57.Expand = false;
        w57.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox14 = new Gtk.HBox();
        this.hbox14.Name = "hbox14";
        this.hbox14.Spacing = 6;
        // Container child hbox14.Gtk.Box+BoxChild
        this.button3 = new Gtk.Button();
        this.button3.CanFocus = true;
        this.button3.Name = "button3";
        this.button3.UseUnderline = true;
        this.button3.Label = Mono.Unix.Catalog.GetString("Apply");
        this.hbox14.Add(this.button3);
        Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(this.hbox14[this.button3]));
        w58.Position = 2;
        w58.Expand = false;
        w58.Fill = false;
        w58.Padding = ((uint)(6));
        this.vbox2.Add(this.hbox14);
        Gtk.Box.BoxChild w59 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox14]));
        w59.Position = 7;
        w59.Expand = false;
        w59.Fill = false;
        this.notebook3.Add(this.vbox2);
        // Notebook tab
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("Text");
        this.notebook3.SetTabLabel(this.vbox2, this.label5);
        this.label5.ShowAll();
        // Notebook tab
        Gtk.Label w61 = new Gtk.Label();
        w61.Visible = true;
        this.notebook3.Add(w61);
        this.label6 = new Gtk.Label();
        this.label6.Name = "label6";
        this.label6.LabelProp = Mono.Unix.Catalog.GetString("page2");
        this.notebook3.SetTabLabel(w61, this.label6);
        this.label6.ShowAll();
        // Notebook tab
        Gtk.Label w62 = new Gtk.Label();
        w62.Visible = true;
        this.notebook3.Add(w62);
        this.label22 = new Gtk.Label();
        this.label22.Name = "label22";
        this.label22.LabelProp = Mono.Unix.Catalog.GetString("page3");
        this.notebook3.SetTabLabel(w62, this.label22);
        this.label22.ShowAll();
        // Notebook tab
        Gtk.Label w63 = new Gtk.Label();
        w63.Visible = true;
        this.notebook3.Add(w63);
        this.label10 = new Gtk.Label();
        this.label10.Name = "label10";
        this.label10.LabelProp = Mono.Unix.Catalog.GetString("page4");
        this.notebook3.SetTabLabel(w63, this.label10);
        this.label10.ShowAll();
        // Notebook tab
        Gtk.Label w64 = new Gtk.Label();
        w64.Visible = true;
        this.notebook3.Add(w64);
        this.label11 = new Gtk.Label();
        this.label11.Name = "label11";
        this.label11.LabelProp = Mono.Unix.Catalog.GetString("page5");
        this.notebook3.SetTabLabel(w64, this.label11);
        this.label11.ShowAll();
        // Notebook tab
        Gtk.Label w65 = new Gtk.Label();
        w65.Visible = true;
        this.notebook3.Add(w65);
        this.label12 = new Gtk.Label();
        this.label12.Name = "label12";
        this.label12.LabelProp = Mono.Unix.Catalog.GetString("page6");
        this.notebook3.SetTabLabel(w65, this.label12);
        this.label12.ShowAll();
        // Notebook tab
        Gtk.Label w66 = new Gtk.Label();
        w66.Visible = true;
        this.notebook3.Add(w66);
        this.label13 = new Gtk.Label();
        this.label13.Name = "label13";
        this.label13.LabelProp = Mono.Unix.Catalog.GetString("page7");
        this.notebook3.SetTabLabel(w66, this.label13);
        this.label13.ShowAll();
        this.hbox2.Add(this.notebook3);
        Gtk.Box.BoxChild w67 = ((Gtk.Box.BoxChild)(this.hbox2[this.notebook3]));
        w67.Position = 0;
        w67.Padding = ((uint)(6));
        this.vbox4.Add(this.hbox2);
        Gtk.Box.BoxChild w68 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
        w68.Position = 0;
        w68.Padding = ((uint)(6));
        this.hpaned2.Add(this.vbox4);
        this.hpaned1.Add(this.hpaned2);
        this.vbox1.Add(this.hpaned1);
        Gtk.Box.BoxChild w71 = ((Gtk.Box.BoxChild)(this.vbox1[this.hpaned1]));
        w71.Position = 4;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 1102;
        this.DefaultHeight = 782;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
        this.button2.Clicked += new System.EventHandler(this.OnButton2Clicked);
        this.image1.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnImage1ButtonPressEvent);
        this.button3.Clicked += new System.EventHandler(this.OnButton3Clicked);
    }
}
